aptiv-s32g: pfe: don't install pfe by default
Issue: LIN1022-3020

If we install pfe by default and leave PFE_LOCAL_FIRMWARE_DIR as
an NULL, there will be compiling error as below:

ERROR: _exec_cmd: install -m 0644 -D tmp-glibc/deploy/images/aptiv_cvc_sousa/s32g_pfe_class.fw tmp-glibc/work/aptiv_cvc_sousa-wrs-linux/wrlinux-image-std/1.0-r5/tmp-wic/boot.1/s32g_pfe_class.fw returned '1' instead of 0
| output: install: cannot stat 'tmp-glibc/deploy/images/aptiv_cvc_sousa/s32g_pfe_class.fw': No such file or directory

So we need to make both pfe installation and PFE_LOCAL_FIRMWARE_DIR to be
setup manually.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>