aptiv-s32g: atf-s32g: fix undefined reference to `vr5510_register_instance'
Issue: LIN1022-2613

Add the patch 0006-aptiv-set-S32_VR5510-for-aptiv-CVC-platform.patch to
fix the build error which is caused by SDK update.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>