aptiv: atf: update to fix patch applying failures
Issue: LIN1024-2814

This patch is to fix the internal patch applying failure issues, like
following:

  ERROR: atf-s32g-2.10-r0.vr2401 do_patch: Applying patch '0007-aptiv-s32g-atf-s32g-Patch-PFE1-2-SGMII-MDIO-Bus-for-.patch' on target directory '...'
  BBHandledException("Applying '0007-aptiv-s32g-atf-s32g-Patch-PFE1-2-SGMII-MDIO-Bus-for-.patch' failed:
  stdout: checking file fdts/s32g.dtsi
  Hunk #1 FAILED at 554.
  Hunk #2 succeeded at 1215 (offset 647 lines).
  Hunk #3 succeeded at 1267 (offset 647 lines).
  Hunk #4 FAILED at 628.
  2 out of 4 hunks FAILED

  stderr: ")

So update the related internal patches to fix the issue.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>